version: "3.9"
services:
  frontend:
    image: selotapetm/netflix-clone-frontend:5
    networks:
      - public-net-1
    depends_on:
      - api
    environment:
      - MOVIE_CATALOG_SERVICE=http://api:8081
    ports:
      - 3000:3000
  api:
    image: selotapetm/netflix-clone-api:18
    networks:
      - public-net-1
    ports:
      - 8081:8081
  nginx:
    networks:
      - public-net-1
    volumes:
      - /etc/letsencrypt/live/sohord.com/fullchain.pem:/cert/fullchain.pem
      - /etc/letsencrypt/live/sohord.com/privkey.pem:/cert/privkey.pem
    build:
      context: Services/nginx-http-engine
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend

networks:
  public-net-1:
    driver: bridge

