version: "3.9"
services:
  frontend:
    image: selotapetm/netflix-clone-frontend:1.0.0
    networks:
      - public-net-1
    depends_on:
      - api
    environment:
      - MOVIE_CATALOG_SERVICE=http://api:8081
    ports:
      - 3000:3000
  api:
    image: selotapetm/netflix-clone-api:1.0.0
    networks:
      - public-net-1
    ports:
      - 8081:8081
  nginx:
    networks:
      - public-net-1
    volumes:
      - /etc/letsencrypt/live/sohord.com/fullchain.pem:/cert/fullchain.pem
      - /etc/letsencrypt/live/sohord.com/privkey.pem:/cert/privkey.pem
    build:
      context: Services/nginx-http-engine
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
  influxdb:
    networks:
      - public-net-1
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
  grafana:
    networks:
      - public-net-1
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3030:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana

networks:
  public-net-1:
    driver: bridge

