name: CI/CD for NetflixMovieCatalog

on:
  push:
    branches:
      - main
    paths:
      - 'Services/NetflixMovieCatalog/**'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'SeloTapeTM'
          git config --global user.email 'SeloTapeTM@users.noreply.github.com'
          git pull

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image for API service
        run: |
          IMAGE_TAG=selotapetm/netflix-clone-api:$GITHUB_RUN_NUMBER
          docker build -t $IMAGE_TAG ./Services/NetflixMovieCatalog
          echo "::set-output name=image_tag::$IMAGE_TAG"

      - name: Push Docker image to registry
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push selotapetm/netflix-clone-api:$GITHUB_RUN_NUMBER
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

      - name: Update Docker Compose Image Tags
        run: |
          git checkout release
          git pull
          sed -i "s/selotapetm\/netflix-clone-api:.*/selotapetm\/netflix-clone-api:$GITHUB_RUN_NUMBER/g" docker-compose.yaml

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Committed new docker-compose with $GITHUB_RUN_NUMBER version of service api"
          git push
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Deploy to EC2
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          touch ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@18.199.116.222 "cd /home/ubuntu/NetflixCloneProject/Services && git pull"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@18.199.116.222 "compose"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}